### DISCUSSION TITLE
From opentelemetry-otlp@16: `trait `opentelemetry::trace::tracer::Tracer` is not implemented for `opentelemetry_sdk::trace::Tracer``

### DISCUSSION THREAD

**Discussion by frederikhors** [open-telemetry/opentelemetry-rust#1779] [Q&A]
With these deps:

```toml
opentelemetry = { version = "0.22.0", default-features = false, features = [
    "trace",
] }
opentelemetry-http = { version = "0.11.1", default-features = false }
opentelemetry-otlp = { version = "0.15.0", default-features = false, features = [
    "http-proto",
] }
opentelemetry_sdk = { version = "0.22", default-features = false, features = [
    "rt-tokio",
] }
```

I'm using:

```rust
let otlp_tracer = opentelemetry_otlp::new_pipeline()
    .tracing()
    .with_exporter(exporter)
    .with_trace_config(trace::config().with_resource(Resource::new(vec![
        KeyValue::new("service.name", service_name.to_string()),
    ])))
    .with_batch_config(
        trace::BatchConfigBuilder::default()
            .with_max_export_batch_size(10_000)
            .with_max_queue_size(30_000)
            .with_scheduled_delay(Duration::from_millis(5_000))
            .build(),
    )
    .install_batch(opentelemetry_sdk::runtime::Tokio)
    .unwrap();

let layer = tracing_opentelemetry::layer()
    .with_tracer(otlp_tracer)
    .with_filter(EnvFilter::from("info"))
    .boxed();
```

and it works.

Now with these deps:

```toml
opentelemetry = { version = "0.23.0", default-features = false, features = [
    "trace",
] }
opentelemetry-http = { version = "0.12.0", default-features = false }
opentelemetry-otlp = { version = "0.16.0", default-features = false, features = [
    "http-proto",
] }
opentelemetry_sdk = { version = "0.23", default-features = false, features = [
    "rt-tokio",
] }
```

I'm getting this error:

```
error[E0277]: the trait bound `opentelemetry_sdk::trace::Tracer: opentelemetry::trace::tracer::Tracer` is not satisfied
    |
91  |             .with_tracer(otlp_tracer)
    |              ----------- ^^^^^^^^^^^ the trait `opentelemetry::trace::tracer::Tracer` is not implemented for `opentelemetry_sdk::trace::Tracer`
    |              |
    |              required by a bound introduced by this call
    |
    = help: the following other types implement trait `opentelemetry::trace::tracer::Tracer`:
              opentelemetry::global::trace::BoxedTracer
              opentelemetry_sdk::trace::tracer::Tracer
              opentelemetry::trace::noop::NoopTracer
note: required by a bound in `tracing_opentelemetry::OpenTelemetryLayer::<S, T>::with_tracer`
   --> C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tracing-opentelemetry-0.23.0\src\layer.rs:581:17
    |
579 |     pub fn with_tracer<Tracer>(self, tracer: Tracer) -> OpenTelemetryLayer<S, Tracer>
    |            ----------- required by a bound in this associated function
580 |     where
581 |         Tracer: otel::Tracer + PreSampledTracer + 'static,
    |                 ^^^^^^^^^^^^ required by this bound in `OpenTelemetryLayer::<S, T>::with_tracer`
```

How can I fix?

**Comment by zoer** [comment]
I had a similar problem and solved it by adjusting the crate versions. Here are the dependencies that worked for me:
```toml
tracing-subscriber = { version= "0.3.18", features = ["env-filter"]}
tracing = "0.1.40"
tracing-opentelemetry = "0.23.0"
opentelemetry-jaeger = { version = "0.21.0", features = ["full"] }
opentelemetry = "0.22.0"
opentelemetry_sdk = { version = "0.22.1", features = [ "rt-tokio", "rt-tokio-current-thread"] }
opentelemetry-jaeger-propagator = "0.1.0"
opentelemetry-otlp = { version = "0.15.0", features = ["tokio"]}
opentelemetry-semantic-conventions = "0.15.0"
```
