### ISSUE TITLE
which version of crate to use 

### ISSUE THREAD

**Issue by ivanitskiy** [open-telemetry/opentelemetry-rust#1139]
I tried to follow `./opentelemetry-otlp/examples/basic-otlp` code to instrument my rust project, but could not find the right versions to use as it seems there was a major refactoring and now it not compatible (or versions were not updated) but without relative path and used `cargo add` to add depedencies

```toml
[dependencies]
once_cell = "1.17"
opentelemetry_api = { version = "0.19.0", features = ["metrics"] }
opentelemetry_sdk = { version = "0.19.0", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.12.0", features = ["tonic", "metrics"] }
opentelemetry-semantic-conventions = { version = "0.11.0" }
tokio = { version = "1.0", features = ["full"] }
```

I published a repo https://github.com/ivanitskiy/otlp-demo-issue  that contains those only version changes that can be used to repro like. the original code is from mentioned example as of today [link](https://github.com/open-telemetry/opentelemetry-rust/tree/e773f922632a1858004f04a83b95a227ee8f3dfa/opentelemetry-otlp/examples/basic-otlp):
```shell
git clone https://github.com/ivanitskiy/otlp-demo-issue 
cd otlp-demo-issue 
cargo run
```
please advice which version to use or which examples are working with most recent versions?
