### ISSUE TITLE
[Bug]: Context::current().with_remote_span_context() not working

### ISSUE THREAD

**Issue by hkford** [open-telemetry/opentelemetry-rust#1604]
### What happened?

I try generating span with remote span context. 
I generate trace using `tracing` and associate it with a OpenTelemetry trace using [`set_parent()`](https://docs.rs/tracing-opentelemetry/0.23.0/tracing_opentelemetry/trait.OpenTelemetrySpanExt.html#tymethod.set_parent). The parameter of set_parent() is Context so I generate Context using [`Context.with_remote_span_context()`](https://docs.rs/opentelemetry/latest/opentelemetry/trace/trait.TraceContextExt.html#tymethod.with_remote_span_context).

```rust
use lambda_runtime::Error;
use opentelemetry::trace::SpanContext;
use opentelemetry::trace::TracerProvider as _;
use opentelemetry::Context;
use opentelemetry_aws::trace::xray_propagator::span_context_from_str;

use opentelemetry_sdk::trace::TracerProvider;

use tracing::{info, info_span};
// For using subscriber.with()
use tracing_subscriber::prelude::__tracing_subscriber_SubscriberExt;
use tracing_subscriber::util::SubscriberInitExt;
use tracing_subscriber::{fmt, fmt::format, EnvFilter};
// For using span.context()
use tracing_opentelemetry::OpenTelemetrySpanExt;
// For using Context.with_remote_span_context()
use opentelemetry::trace::TraceContextExt;
fn init_observability() {
    let exporter = opentelemetry_otlp::new_exporter()
        .tonic()
        .build_span_exporter()
        .expect("Failed to build span exporter");
    // Create a new OpenTelemetry trace pipeline that prints to stdout
    let provider = TracerProvider::builder()
        .with_simple_exporter(exporter)
        .build();
    let tracer = provider.tracer("lambda");
    let fmt_layer = fmt::layer().event_format(format().json());
    let filter_layer = EnvFilter::from_default_env();
    let telemetry_layer = tracing_opentelemetry::layer().with_tracer(tracer);

    tracing_subscriber::registry()
        .with(filter_layer)
        .with(fmt_layer)
        .with(telemetry_layer)
        .init();
}
fn retrieve_span_context_from_xray_traceid(xray_trace_id: &str) -> Result<SpanContext, Error> {
    span_context_from_str(xray_trace_id).ok_or("Invalid _X_AMZN_TRACE_ID".into())
}

#[tokio::main]
async fn main() {
    init_observability();
    let _r = run().expect("Run failed");
}

fn run() -> Result<(), Error> {
    let xray_trace_id = "Root=1-65dc5008-1561ed7046ffcbcb114af027;Parent=b510129166d5a083;Sampled=1;Lineage=f98dd9ff:0";
    let parent_spancontext = retrieve_span_context_from_xray_traceid(&xray_trace_id)?;

    info!("Prent SpanContext is not empty: {:?}", &parent_spancontext);
    let span = info_span!("Handler is called");

    let ctx = Context::current().with_remote_span_context(parent_spancontext);
    info!("Context with remote_span_context is {:?}", ctx);
    info!("Span before set_parent is {:?}", span.context());
    span.set_parent(ctx);

    info!("Span after set_parent is {:?}", span.context());
    Ok(())
}
```

Running `RUST_LOG=info cargo run` and I saw span has no span in its context after set_parent.

```
{"timestamp":"2024-03-06T09:03:32.739847Z","level":"INFO","fields":{"message":"Prent SpanContext is not empty: SpanContext { trace_id: 65dc50081561ed7046ffcbcb114af027, span_id: b510129166d5a083, trace_flags: TraceFlags(1), is_remote: true, trace_state: TraceState(Some([(\"lineage\", \"f98dd9ff:0\")])) }"},"target":"playground"}
{"timestamp":"2024-03-06T09:03:32.739977Z","level":"INFO","fields":{"message":"Context with remote_span_context is Context { entries: 0 }"},"target":"playground"}
{"timestamp":"2024-03-06T09:03:32.740000Z","level":"INFO","fields":{"message":"Span before set_parent is Context { entries: 0 }"},"target":"playground"}
{"timestamp":"2024-03-06T09:03:32.740016Z","level":"INFO","fields":{"message":"Span after set_parent is Context { entries: 0 }"},"target":"playground"}
```

### API Version

Cargo.toml
```toml
tracing = { version = "0.1.40", features = ["log","attributes"] }
tracing-subscriber = { version = "0.3.18", features = ["std", "env-filter","json"] }
opentelemetry = { version = "0.22.0" }
opentelemetry_sdk = { version = "0.22.0", features = ["rt-tokio"] }
opentelemetry-aws = "0.10.0"
opentelemetry-otlp = { version = "0.15.0", features = ["grpc-tonic", "tls"] }
tracing-opentelemetry = "0.23.0"
```

### SDK Version

Cargo.toml
```toml
tracing = { version = "0.1.40", features = ["log","attributes"] }
tracing-subscriber = { version = "0.3.18", features = ["std", "env-filter","json"] }
opentelemetry = { version = "0.22.0" }
opentelemetry_sdk = { version = "0.22.0", features = ["rt-tokio"] }
opentelemetry-aws = "0.10.0"
opentelemetry-otlp = { version = "0.15.0", features = ["grpc-tonic", "tls"] }
tracing-opentelemetry = "0.23.0"
```

### What Exporters are you seeing the problem on?

OTLP
