### ISSUE TITLE
[Bug]: Issue creating new TextMapPropagator with opentelemetry_zipkin::Propagator

### ISSUE THREAD

**Issue by Red3nzo** [open-telemetry/opentelemetry-rust#1848]
### What happened?

Try to follow the docs & get this nasty error:
```rs
5  |     opentelemetry::global::set_text_map_propagator(opentelemetry_zipkin::Propagator::new());
   |     ---------------------------------------------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `TextMapPropagator` is not implemented for `Propagator`
   |     |
   |     required by a bound introduced by this call
   |
   = help: the following other types implement trait `TextMapPropagator`:
             BaggagePropagator
             TextMapCompositePropagator
             TraceContextPropagator
note: required by a bound in `set_text_map_propagator`
```
The following functions is:
```rs
use tracing_subscriber::layer::SubscriberExt;
use tracing_subscriber::EnvFilter;

pub fn configure_tracing(level: String, service_name: String) {
    opentelemetry::global::set_text_map_propagator(opentelemetry_zipkin::Propagator::new()); // <------ ERROR

    let tracer = opentelemetry_zipkin::new_pipeline().install_simple().unwrap();

    let tracer = tracing_opentelemetry::layer().with_tracer(tracer);

    let subscriber = tracing_subscriber::fmt::layer().json();

    let level = EnvFilter::new(level);

    tracing_subscriber::registry()
        .with(subscriber)
        .with(level)
        .with(tracer)
        .init();
}
```

I'm unsure how to continue with the zipkin implementation. Does anyone have any advice?

### API Version

0.23.0

### SDK Version

0.23.0

**Comment by cijothomas** [comment]
Most likely version issue, especially since tracing-opentelemetry is also involved. Can you share cargo.toml file as well?

**Comment by Red3nzo** [comment]
@cijothomas Here are the related crates.

```toml
tracing = { version = "0.1", features = ["attributes"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json", "time"] }
tracing-opentelemetry = "0.17"
opentelemetry = { version = "*", features = ["rt-tokio", "tokio", "metrics"] }
opentelemetry_sdk = "0.23"
opentelemetry-zipkin = { version = "*", features = ["reqwest-client"], default-features = false }
```
