### ISSUE TITLE
[Bug]: otlp example does not work without configuration update

### ISSUE THREAD

**Issue by krlohnes** [open-telemetry/opentelemetry-rust#1998]
### What happened?

I tried to run [basic-otlp example](https://github.com/open-telemetry/opentelemetry-rust/tree/main/opentelemetry-otlp/examples/basic-otlp) and it simply didn't work.

I update the first section of otel-collector-config.yml to the following
```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
```
and it started working.

### API Version

0.24.0

### SDK Version

0.24.1

### What Exporter(s) are you seeing the problem on?

OTLP

### Relevant log output

```shell
OpenTelemetry log error occurred. Exporter otlp encountered the following errors: the grpc server returns error (The operation was cancelled): , detailed error message: operation was canceled
```
