### ISSUE TITLE
[Feature]: please add extra detail to global errors when TLS feature missing

### ISSUE THREAD

**Issue by davidhewitt** [open-telemetry/opentelemetry-rust#2169]
### Related Problems?

Consider a basic example like below (will need an appropriate write token for logfire.dev if you actually want to run this):

```toml title="Cargo.toml"
[package]
name = "otel-example"
version = "0.1.0"
edition = "2021"

[dependencies]
opentelemetry = { version = "*", default-features = false, features = ["trace"] }
# XXX: `reqwest-rustls` feature (or any other TLS feature) is missing
opentelemetry-otlp = { version = "*", default-features = false, features = ["trace", "http-proto", "reqwest-blocking-client"] }
```

```rust title="src/main.rs"
use opentelemetry::{
    global::ObjectSafeSpan,
    trace::{Tracer, TracerProvider},
};

fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    let otlp_exporter = opentelemetry_otlp::new_exporter()
        .http()
        .with_protocol(opentelemetry_otlp::Protocol::HttpBinary)
        // XXX: sending to https endpoint without TLS feature enabled
        .with_endpoint("https://logfire-api.pydantic.dev/v1/traces")
        .with_headers({
            let mut headers = std::collections::HashMap::new();
            headers.insert(
                "Authorization".into(),
                "<add a write token here>".into(),
            );
            headers
        });

    let tracer_provider = opentelemetry_otlp::new_pipeline()
        .tracing()
        .with_exporter(otlp_exporter)
        .install_simple()?;
    let tracer = tracer_provider.tracer("my_tracer");

    tracer.span_builder("Hello World").start(&tracer).end();

    Ok(())
}
```

The output from this will be:

```
$ cargo run
   [...]
     Running `target/debug/otel-example`
OpenTelemetry trace error occurred. error sending request for url (https://logfire-api.pydantic.dev/v1/traces)
```

What's happened, is that the connection failed due to lack of TLS.

### Describe the solution you'd like:

It would be great if the error printed could provide more details.

Due to the error being swallowed by a global error handler, I couldn't find a way to get more details on the error without some debugging / patching deep into the guts of the opentelemetry SDK.
