### ISSUE TITLE
Missing methods ::builder in v0.26.0 for Exporters

### ISSUE THREAD

**Issue by simone-sanfratello** [open-telemetry/opentelemetry-rust#2270]
Hello,

I'm trying to run the example in https://github.com/open-telemetry/opentelemetry-rust/tree/main/opentelemetry-otlp/examples/basic-otlp-http

The example works fine as it is, but using the crates from the registry as 

```toml
opentelemetry = { version = "0.26.0" }
opentelemetry_sdk = { version = "0.26.0", features = ["rt-tokio", "metrics", "logs"]}
opentelemetry-http = { version = "0.26.0", optional = true, default-features = false}
opentelemetry-otlp = { version = "0.26.0", features = ["http-proto", "http-json", "logs"] , default-features = false}
opentelemetry-appender-tracing = { version = "0.26.0", default-features = false}
opentelemetry-semantic-conventions = { version = "0.26.0" }
```

the `LogExporter`, `SpanExporter` and `MetricExporter` doesn't have the builder methods

I suppose the version on the registry is still the 0.25.0, looks like it's not consistent with the [changelog](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-otlp/CHANGELOG.md#v0260) because also the `Metric` types for example are still plural
