### ISSUE TITLE
there is no reactor running, must be called from the context of a Tokio 1.x runtime

### ISSUE THREAD

**Issue by maxwellflitton** [open-telemetry/opentelemetry-rust#2673]
I'm trying to get the batch exporter with `reqwest` working in `Tokio` but I'm getting the following error:

```
there is no reactor running, must be called from the context of a Tokio 1.x runtime
```
I've read through docs, pull requests, and other issues and I can't find any reference on how to solve this. 

I've got the following dependencies for my logging crate:

```toml
tracing = { version = "0.1", optional = true}
opentelemetry-appender-tracing = { version = "0.28.1", optional = true}
tracing-subscriber = { version = "0.3", features = ["std", "env-filter", "fmt", "registry"], optional = true}
tracing-opentelemetry = { version = "0.29.0", optional = true}
opentelemetry = { version = "0.28.0", features = ["trace"], optional = true }
opentelemetry_sdk = { version = "0.28.0", features = ["rt-tokio", "metrics", "spec_unstable_metrics_views"], optional = true }
opentelemetry-stdout = { version = "0.28.0", optional = true }
tokio = { version = "1.43.0", features = ["full"] }  # at this point we will be using Tokio for logs for different tracing providers 
opentelemetry-otlp = { version = "0.28.0", features = ["http-json", "reqwest-client"], optional = true }
reqwest = { version = "0.12.12", features = ["json"], optional = true}
tracing-attributes = { version = "0.1.24", optional = true }
```

And below is how I `init` the log provider:

```rust
use opentelemetry_appender_tracing::layer;
use opentelemetry_otlp::{WithExportConfig, WithHttpConfig};
use opentelemetry_sdk::logs::SdkLoggerProvider;
use opentelemetry_sdk::Resource;
use std::{error::Error, sync::OnceLock};
use tracing_subscriber::{prelude::*, EnvFilter};

pub fn init_log_provider<X, T>(service_name: X, endpoint: T) -> SdkLoggerProvider
where
    X: ToString + Into<opentelemetry::Value>,
    T: Into<String>,
{
    let client = reqwest::Client::new();
    let exporter = opentelemetry_otlp::LogExporter::builder()
        .with_http()
        .with_endpoint(endpoint)
        .with_protocol(opentelemetry_otlp::Protocol::HttpJson)
        .with_http_client(client)
        .build()
        .unwrap();

    let provider = SdkLoggerProvider::builder()
        .with_batch_exporter(exporter)
        .with_resource(Resource::builder().with_service_name(service_name).build())
        .build();

    return provider
}
```

Inside a server calling this I have the following dependencies:

```toml
[dependencies]
actix-web = "4.9.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
logging-lib = { path = "../../../crates/logging-lib", features = ["otel"] }
tokio = { version = "1.1.0", features = ["full"]}
```

And I have the following `main`:

```rust
use actix_web::{get, post, web, App, HttpServer, Responder};
use logging_lib as myotel;
use myotel::opentelemetry_appender_tracing::layer;
use myotel::tracing::{info, span, Level};
use myotel::tracing_subscriber::{prelude::*, EnvFilter};

use myotel::providers::otel::{
    logging::init_log_provider,
};

#[get("/increase_count")]
async fn increase() -> impl Responder {
    println!("increasing the count");
    info!("increasing the count");
    "increasing the count"
}

#[get("/force_error")]
async fn force_error() -> impl Responder {
    println!("forcing an error");
    info!("forcing an error");
    "forcing error"
}

#[tokio::main]
async fn main() -> std::io::Result<()> {
    let log_provider = init_log_provider("test-service", "http://localhost:4318/v1/traces");
    // Create a new OpenTelemetryTracingBridge using the above LoggerProvider.
    let otel_layer = layer::OpenTelemetryTracingBridge::new(&log_provider);
    let filter_otel = EnvFilter::new("info")
        .add_directive("hyper=off".parse().unwrap())
        .add_directive("opentelemetry=off".parse().unwrap())
        .add_directive("tonic=off".parse().unwrap())
        .add_directive("h2=off".parse().unwrap())
        .add_directive("reqwest=off".parse().unwrap());
    let otel_layer = otel_layer.with_filter(filter_otel);

    // Create a new tracing::Fmt layer to print the logs to stdout. It has a
    // default filter of `info` level and above, and `debug` and above for logs
    // from OpenTelemetry crates. The filter levels can be customized as needed.
    let filter_fmt = EnvFilter::new("info").add_directive("opentelemetry=debug".parse().unwrap());
    let fmt_layer = myotel::tracing_subscriber::fmt::layer()
        .with_thread_names(true)
        .with_filter(filter_fmt);

    // Initialize the tracing subscriber with the OpenTelemetry layer and the
    // Fmt layer.
    myotel::tracing_subscriber::registry()
        .with(otel_layer)
        .with(fmt_layer)
        .init();
    HttpServer::new(|| App::new().service(increase).service(force_error))
        .bind("127.0.0.1:8081")?
        .run()
        .await
}
```
But I get the following error:

```
2025-02-15T15:08:54.629521Z  INFO main actix_server::builder: starting 16 workers
2025-02-15T15:08:54.629727Z  INFO main actix_server::server: Tokio runtime found; starting in existing Tokio runtime
2025-02-15T15:08:54.629850Z  INFO main actix_server::server: starting service: "actix-web-service-127.0.0.1:8081", workers: 16, listening on: 127.0.0.1:8081
2025-02-15T15:08:55.631190Z DEBUG OpenTelemetry.Logs.BatchProcessor opentelemetry_sdk:  name="BatchLogProcessor.ExportingDueToTimer"
2025-02-15T15:08:55.631680Z DEBUG OpenTelemetry.Logs.BatchProcessor opentelemetry-otlp:  name="HttpLogsClient.CallingExport"
2025-02-15T15:08:55.631755Z DEBUG OpenTelemetry.Logs.BatchProcessor opentelemetry-http:  name="ReqwestClient.Send"
thread 'OpenTelemetry.Logs.BatchProcessor' panicked at C:\Users\GBFlittMa\.cargo\registry\src\index.crates.io-6f17d22bba15001f\hyper-util-0.1.10\src\client\legacy\connect\dns.rs:122:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It used to work when I referenced the `Tokio` runtime directly however, I can't seem to find any references to runtimes in the any of the docs in any of the otel crates. Hopefully I'm missing something small. Will happily write up a guide once this is working to help others.
