### ISSUE TITLE
opentelemetry-zipkin 0.28.0 no longer exporting successfully - seems to stall at connection stage

### ISSUE THREAD

**Issue by jpoisso** [open-telemetry/opentelemetry-rust#2739]
Hello!

I have an application deployed in production that uses Actix Web along with Reqwest and opentelemetry to generate and export traces.

The current deployment works just fine on 0.27 but after migrating to 0.28 and adapting the signature, the export portion no longer completes and it hangs on API requests.

```toml
actix-web = { version = "4.9.0", features = ["actix-tls", "rustls-0_23", "default"], default-features = false }
actix-web-prometheus = { version = "0.1.2", features = ["process"], default-features = false }
actix-web-opentelemetry = { version = "0.21.0", features = [ "metrics", "metrics-prometheus"], default-features = false }
actix-web-codegen = { version = "4.3.0", features = ["default"], default-features = false }
actix-cors = { version = "0.7.0", default-features = false }
actix-tls =  { version = "3.4.0", features = ["rustls-0_23", "accept", "connect", "uri"], default-features = false }
actix-files = { version = "0.6.6", default-features = false }
reqwest = { version = "0.12.12", features = ["rustls-tls", "socks", "json", "stream", "http2", "h2", "cookies", "brotli", "multipart", "charset", "deflate", "gzip", "zstd"], default-features = false }
reqwest-middleware = { version = "0.4.1", features = ["rustls-tls", "http2", "json", "charset", "multipart"], default-features = false }
reqwest-tracing = { version = "0.5.6", features = ["opentelemetry_0_28"], default-features = false  }
rustls = { version = "0.23.23", features=["default", "brotli", "hashbrown", "prefer-post-quantum", "read_buf", "zlib", "logging", "tls12", "aws-lc-rs"], default-features = false }
rustls-pemfile = { version = "2.2.0", features=["std"], default-features = false }
opentelemetry = { version = "0.28.0", features = ["default"], default-features = false}
opentelemetry_sdk = { version = "0.28.0", features = ["rt-tokio", "tokio", "trace", "logs"], default-features = false}
opentelemetry-zipkin = { version = "0.28.0", features = ["reqwest-client"], default-features = false }
opentelemetry-http  = { version = "0.28.0", features = ["reqwest"], default-features = false}
```

```rust
global::set_text_map_propagator(opentelemetry_zipkin::Propagator::new());

// let zipkin_pipeline = opentelemetry_zipkin::new_pipeline()
//     .with_service_name(app_name)
//     .with_collector_endpoint(url)
//     .with_trace_config(Config::default())
//     .with_http_client(http_client)
//     .install_batch(opentelemetry_sdk::runtime::Tokio)
//     .map_err(|e| {
//         AppError::ServerError(format!("failed to setup zipkin pipeline: {e:?}."))
//     })?;

let exporter = ZipkinExporter::builder()
    .with_collector_endpoint(url)
    .with_http_client(http_client)
    .build()
    .map_err(|e| AppError::ServerError(format!("failed to setup zipkin exporter: {e:?}.")))?;

let provider = SdkTracerProvider::builder()
 .with_simple_exporter(exporter)
 .with_sampler(Sampler::AlwaysOn)
 .with_resource(
     Resource::builder_empty()
         .with_service_name(app_name)
         .build(),
 )
 .with_id_generator(RandomIdGenerator::default())
 .build();
```

I tried hitting our deployed Zipkin instance which uses TLS, and also a local docker instance (HTTP), both have the same behavior.

I tried with and without our custom Reqwest client as well.

```text
2025-03-03T14:32:42.015017Z TRACE hyper_util::client::legacy::pool: checkout waiting for idle connection: ("http", 127.0.0.1:9411)
2025-03-03T14:32:42.015072Z TRACE hyper_util::client::legacy::connect::http: Http::connect; scheme=Some("http"), host=Some("127.0.0.1"), port=Some(Port(9411))
2025-03-03T14:32:42.015105Z DEBUG hyper_util::client::legacy::connect::http: connecting to 127.0.0.1:9411
```

It stalls at the `hyper_util::client::legacy::connect::http: connecting to 127.0.0.1:9411` stage and locks up.   

Has anyone else encountered this?
