### ISSUE TITLE
feat(opentelemetry-jaeger): Add feature to enable statically linking isahc

### ISSUE THREAD

**Issue by kjvalencik** [open-telemetry/opentelemetry-rust#374]
# Summary

Default features in `isahc` are disabled which includes statically linking cURL. Add a feature flag to `opentelemetry-jaeger` to enable static linking.

## Use Case

Some environments do not have a system libcurl or may have an incompatible version. For example, iOS.

## API Sketch

```toml
opentelemetry-jaeger = { version = "0.9", features = ["collector_client", "static_curl"] }
```

```toml
[features]
collector_client = ["isahc", "http"]
static_curl = ["isahc/static-curl"]
```
