### ISSUE TITLE
TraceError wrong number of type arguments: expected 1, found 2

### ISSUE THREAD

**Issue by mikeumus** [open-telemetry/opentelemetry-rust#461]
``` rust
use opentelemetry::global;
use opentelemetry::sdk::{
    metrics::PushController, 
    export::ExportError,
    trace as sdktrace
};
use opentelemetry::trace::TraceError;
use opentelemetry::{
    baggage::BaggageExt,
    metrics::{self, MetricsError, ObserverResult, BoundCounter, BoundValueRecorder},
    trace::{TraceContextExt, Tracer},
    Context, Key, KeyValue,
};
use std::time::Duration;
use std::error::Error;
```

`init_tracer()`
<img width="699" alt="Screen Shot 2021-02-26 at 2 13 10 AM" src="https://user-images.githubusercontent.com/57934/109267818-30c83300-77d8-11eb-842e-41bcbd62363c.png">

``` rust
fn init_tracer() -> Result<(sdktrace::Tracer, opentelemetry_jaeger::Uninstall), TraceError> {
    opentelemetry_jaeger::new_pipeline()
        .with_service_name("trace-rust-cli")
        .with_collector_endpoint("https://trace.filevacuum.com:2053/api/traces")
        .with_tags(vec![
            KeyValue::new("Process", "Rust"),
        ])
        .install()
}
```

`🟥 init_tracer() signature error`
```
pub enum TraceError
wrong number of type arguments: expected 1, found 2

unexpected type argumentrustc(E0107)
```
`🟥 init_tracer() return error`
``` 
mismatched types

expected struct `std::io::Error`, found enum `opentelemetry::trace::TraceError`

note: expected enum `std::result::Result<_, std::io::Error>`
         found enum `std::result::Result<_, opentelemetry::trace::TraceError>`rustc(E0308)
lib.rs(2233, 21): expected `std::result::Result<(opentelemetry::sdk::trace::Tracer, opentelemetry_jaeger::Uninstall), std::io::Error>` because of return type
```

`cargo.toml`
``` toml
[dependencies]
blake2 = "0.9.1"
chrono = "0.4.19"
clap = "2.33.3"
digest = "0.9.0"
http = "0.2.3"
indicatif = "0.15.0"
itertools = "0.9.0"
lazy_static = "1.4.0"
opentelemetry = { version = "*", features = ["serialize", "metrics", "trace"]}
opentelemetry-jaeger = { version = "*", features = ["reqwest_blocking_collector_client"] }
prometheus = { version = "0.11.0", features = ["push"] }
regex = "1.4.2"
reqwest = { version = "0.11.1", features = ["blocking", "json"] }
# serde_json = "1.0"
structopt = "0.3.20"
toml = "0.5.7"
# thrift = "0.13"
zip = "0.5.8"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
```

Been stuck on this. Following the examples and docs closely:
- Jaeger `TraceError ` example: https://github.com/open-telemetry/opentelemetry-rust/blob/main/examples/basic/src/main.rs
- `TraceError ` docs.rs: https://docs.rs/opentelemetry/0.12.0/opentelemetry/index.html
