### ISSUE TITLE
opentelemetry_jaeger fails to send packets if the agent_endpoint uses a port other than 6831

### ISSUE THREAD

**Issue by gcharnock** [open-telemetry/opentelemetry-rust#686]
If you change the agent endpoint to some port other than 6831 then no UDP messages get sent. I've verified this with wireshark. There's no error messages generated by the binary or anything to indicate that something is wrong.

`main.rs`
```rust
use opentelemetry::trace::Tracer;
use opentelemetry::global;

fn main() -> Result<(), opentelemetry::trace::TraceError> {
    global::set_text_map_propagator(opentelemetry_jaeger::Propagator::new());
    let tracer = opentelemetry_jaeger::new_pipeline()
        //.with_agent_endpoint("127.0.0.1:6831")   // works
        .with_agent_endpoint("127.0.0.1:10000") // doesn't work
        .install_simple()?;

    tracer.in_span("doing_work", |cx| {
        // Traced app logic here...
    });

    global::shutdown_tracer_provider(); // export remaining spans

    Ok(())
}
```
`cargo.toml`
```toml
[package]
name = "jaeger-bug"
version = "0.1.0"
edition = "2021"

[dependencies]
opentelemetry = "0.16.0"
opentelemetry-jaeger = "0.15.0"

```
Interestingly, I also tried editing the `DEFAULT_AGENT_ENDPOINT` constant in [opentelemetry_jaeger::exporter](https://github.com/open-telemetry/opentelemetry-rust/blob/482772f2317e242e6b98bfe04ed42e4dac8cf77b/opentelemetry-jaeger/src/exporter/mod.rs#L57) and got the same problem without calling `.with_agent_endpoint()`.
