### ISSUE TITLE
OpenTelemetry trace error occurred. Exporter jaeger encountered the following error(s): thrift agent failed with not open

### ISSUE THREAD

**Issue by Abhicodes-crypto** [open-telemetry/opentelemetry-rust#796]
When I send requests to server between the logs i keep getting this 

`OpenTelemetry trace error occurred. Exporter jaeger encountered the following error(s): thrift agent failed with not open`

Can someone please help me resolve this.

**Comment by TommyCpp** [comment]
Could you provide more details? For example, what's your setup. Did you test your agent running alongside the application?

**Comment by deeprobin** [comment]
I have the same error (using docker):

```yml
version: "3.9"
services:
  host:
    build:
      context: .
      dockerfile: ./docker/host.Dockerfile
    environment:
      - JAEGER_SERVICE_NAME=trade-host
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
    ports:
      - "4001:4001"
    depends_on:
      - jaeger
    networks:
      - deeptrading
  node:
    build:
      context: .
      dockerfile: ./docker/node.Dockerfile
    environment:
      - HOST_HOST=host
      - PORT_PORT=4001
    deploy:
      replicas: 2
    networks:
      - deeptrading
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - deeptrading

networks:
  deeptrading:
```

For tracing I use the tokio-tracing library within this tracer:
```rs
    let tracer = opentelemetry_jaeger::new_pipeline()
        .with_service_name("trade-host")
        .install_simple()
        .expect("Failed to initialize OpenTelemetry-Jaeger pipeline");
```
