### ISSUE TITLE
Cargo docs failed due opentelemetry-proto

### ISSUE THREAD

**Issue by agomezru** [open-telemetry/opentelemetry-rust#879]
I have a gitlab pipeline in where I'm getting the documentation of the project. 
Gitlab.yaml file:

```
pages:
  stage: doc
  tags:
    - multi-thread
  script:
    - cargo doc --no-deps --document-private-items
    - mv target/doc ../../public
```

It was working perfectly until I added opentelemetry:

```

use opentelemetry::{Key, KeyValue, Value};
use std::borrow::Cow;

/// a key for our tags.
/// The tags will be appended to the key as an array of strings
pub const DOMAIN_TAGS: Key = Key::from_static_str("domain.com/tags");
```

![image](https://user-images.githubusercontent.com/18211900/190895030-e83017e5-2e29-4c3b-958d-1f6f42b82104.png)

It is weird 'cause its not failing at cargo build. 

I tried to add:
```

    - git submodule init
    - git submodule update
```

After finding that: 
https://github.com/open-telemetry/opentelemetry-rust/issues/751

But still unsuccess. 
Thanks in advance.
