### ISSUE TITLE
OOM Killed when collector client can not connect

### ISSUE THREAD

**Issue by thedodd** [open-telemetry/opentelemetry-rust#956]
Over the course of some time, perhaps due to collector maintenance or other circumstances, the OTEL tracing mechanism seems to run into an issue where it goes into a VERY hot loop, spams the following error message to stdout/stderr (`OpenTelemetry trace error occurred. cannot send span to the batch span processor because the channel is full`), and then eventually causes the app to be OOM killed due to excess memory usage.

- Definitely need to fix the hot loop;
- Definitely need to purge the buffer instead of continually growing it until reaped;
- Dropping spans is better than causing the app to crash, at least make it configurable;

Deps
```toml
opentelemetry = { version = "0.18", default-features = false, features = ["rt-tokio", "trace"] }
opentelemetry-jaeger = { version = "0.17", default-features = false, features = ["rt-tokio", "collector_client", "reqwest_collector_client"] }
tracing = { version = "0.1", default-features = false, features = ["std", "attributes", "release_max_level_debug"] }
tracing-opentelemetry = { version = "0.18", default-features = false, features = ["tracing-log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "fmt", "json", "smallvec", "std", "tracing-log"] }
```

Initialization
```rust
let tracer = opentelemetry_jaeger::new_collector_pipeline()
    .with_service_name("...")
    .with_reqwest()
    .with_timeout(Duration::from_secs(5))
    .with_batch_processor_config(BatchConfig::default().with_max_export_timeout(Duration::from_secs(5)))
    .install_batch(opentelemetry::runtime::Tokio)?;
let telem = tracing_opentelemetry::layer().with_tracer(tracer);
set_text_map_propagator(JaegerPropagator::new());
```

Env
```env
OTEL_EXPORTER_JAEGER_ENDPOINT="http://tracing-collector-endpoint-which-works-just-fine"
OTEL_EXPORTER_JAEGER_PROTOCOL="udp/thrift.binary"
OTEL_SERVICE_NAME="..."
OTEL_TRACES_SAMPLER="always_on"
```

All usage of tracing throughout the app is via function instrumentation: `#[tracing::instrument(...)]` and various calls to `tracing::debug!/info!/warn!/error!` &c.
