### ISSUE TITLE
opentelemetry-otlp: how to configure the prefix `default_` of the metrics exported to Prometheus

### ISSUE THREAD

**Issue by darkyzhou** [open-telemetry/opentelemetry-rust#967]
I am using OpenTelemetry Collector to receive the otlp metrics from my application and export them to Prometheus.

However I noticed that the metrics shown in Prometheus have a `default_` prefix instead of something like my application's name:

<img width="386" src="https://user-images.githubusercontent.com/7220778/218125041-f16a3887-eb71-44cd-8d61-4b9f6d21a934.png">

I checked both the documentation and the OpenTelemetry's specification and didn't find the configuration for it. Did I miss something? Or is it configured by the Collector? Any help will be appreciated!

My crate versions:
```toml
opentelemetry = { version = "0.18.0", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.11.0", features = ["metrics"] }
```
